/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.operations;

import static com.google.genai.gaos.operations.Operations.RequestOperation;
import static com.google.genai.gaos.utils.Exceptions.unchecked;
import static com.google.genai.gaos.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.SDKConfiguration;
import com.google.genai.gaos.SecuritySource;
import com.google.genai.gaos.models.errors.CreateInteractionClientError;
import com.google.genai.gaos.models.errors.CreateInteractionServerError;
import com.google.genai.gaos.models.errors.GaosApiException;
import com.google.genai.gaos.models.interactions.Interaction;
import com.google.genai.gaos.models.operations.CreateInteractionRequest;
import com.google.genai.gaos.models.operations.CreateInteractionResponse;
import com.google.genai.gaos.utils.AsyncRetries;
import com.google.genai.gaos.utils.BackoffStrategy;
import com.google.genai.gaos.utils.Globals;
import com.google.genai.gaos.utils.HTTPClient;
import com.google.genai.gaos.utils.HTTPRequest;
import com.google.genai.gaos.utils.Headers;
import com.google.genai.gaos.utils.Hook.AfterErrorContextImpl;
import com.google.genai.gaos.utils.Hook.AfterSuccessContextImpl;
import com.google.genai.gaos.utils.Hook.BeforeRequestContextImpl;
import com.google.genai.gaos.utils.Java8Compat;
import com.google.genai.gaos.utils.NonRetryableException;
import com.google.genai.gaos.utils.Options;
import com.google.genai.gaos.utils.Retries;
import com.google.genai.gaos.utils.RetryConfig;
import com.google.genai.gaos.utils.SerializedBody;
import com.google.genai.gaos.utils.Utils.JsonShape;
import com.google.genai.gaos.utils.Utils;
import com.google.genai.gaos.utils.transport.HttpRequest;
import com.google.genai.gaos.utils.transport.HttpResponse;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Exception;
import java.lang.IllegalArgumentException;
import java.lang.Object;
import java.lang.String;
import java.lang.Throwable;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;


public class CreateInteraction {

    static abstract class Base {
        final SDKConfiguration sdkConfiguration;
        final String baseUrl;
        final SecuritySource securitySource;
        final List<String> retryStatusCodes;
        final RetryConfig retryConfig;
        final HTTPClient client;
        final Headers _headers;
        final Globals operationGlobals;

        public Base(
                @Nonnull SDKConfiguration sdkConfiguration, @Nullable Options options,
                Headers _headers) {
            this.sdkConfiguration = sdkConfiguration;
            this._headers =_headers;
            this.baseUrl = this.sdkConfiguration.serverUrl();
            this.securitySource = this.sdkConfiguration.securitySource();
            Optional.ofNullable(options)
                    .ifPresent(o -> o.validate(Java8Compat.listOf(Options.Option.RETRY_CONFIG)));
            this.retryStatusCodes = Java8Compat.listOf("408", "409", "429", "5XX");
            this.retryConfig = Java8Compat.or(Optional.ofNullable(options)
                    .flatMap(Options::retryConfig), sdkConfiguration::retryConfig)
                    .orElse(RetryConfig.builder().attemptCountBackoff(4, BackoffStrategy.builder()
                                    .initialInterval(500, TimeUnit.MILLISECONDS)
                                    .maxInterval(8000, TimeUnit.MILLISECONDS)
                                    .baseFactor((double) (2))
                                    .maxElapsedTime(30000, TimeUnit.MILLISECONDS)
                                    .retryConnectError(true)
                                    .build())
                            .build());
            this.client = this.sdkConfiguration.client();
            this.operationGlobals = new Globals();
            this.sdkConfiguration.globals.getParam("pathParam", "api_version")
                .ifPresent(param -> operationGlobals.putParam("pathParam", "api_version", param));
        }

        Optional<SecuritySource> securitySource() {
            return Optional.ofNullable(this.securitySource);
        }

        BeforeRequestContextImpl createBeforeRequestContext() {
            return new BeforeRequestContextImpl(
                    this.sdkConfiguration,
                    this.baseUrl,
                    "CreateInteraction",
                    java.util.Optional.empty(),
                    securitySource());
        }

        AfterSuccessContextImpl createAfterSuccessContext() {
            return new AfterSuccessContextImpl(
                    this.sdkConfiguration,
                    this.baseUrl,
                    "CreateInteraction",
                    java.util.Optional.empty(),
                    securitySource());
        }

        AfterErrorContextImpl createAfterErrorContext() {
            return new AfterErrorContextImpl(
                    this.sdkConfiguration,
                    this.baseUrl,
                    "CreateInteraction",
                    java.util.Optional.empty(),
                    securitySource());
        }
        <T, U>HttpRequest buildRequest(T request, Class<T> klass, TypeReference<U> typeReference) throws Exception {
            String url = Utils.generateURL(
                    klass,
                    this.baseUrl,
                    "/{api_version}/interactions",
                    request, this.operationGlobals);
            HTTPRequest req = new HTTPRequest(url, "POST");
            Object convertedRequest = Utils.convertToShape(
                    request,
                    JsonShape.DEFAULT,
                    typeReference);
            SerializedBody serializedRequestBody = Utils.serializeRequestBody(
                    convertedRequest,
                    "body",
                    "json",
                    false);
            if (serializedRequestBody == null) {
                throw new IllegalArgumentException("Request body is required");
            }
            req.setBody(Optional.ofNullable(serializedRequestBody));
            req.addHeader("Accept", "application/json;q=1, text/event-stream;q=0")
                    .addHeader("user-agent", SDKConfiguration.USER_AGENT);
            _headers.forEach((k, list) -> list.forEach(v -> req.addHeader(k, v)));
            Utils.configureSecurity(req, this.sdkConfiguration.securitySource().getSecurity());

            return req.build();
        }
    }

    public static class Sync extends Base
            implements RequestOperation<CreateInteractionRequest, CreateInteractionResponse> {
        public Sync(
                @Nonnull SDKConfiguration sdkConfiguration, @Nullable Options options,
                Headers _headers) {
            super(
                  sdkConfiguration, options,
                  _headers);
        }

        private HttpRequest onBuildRequest(CreateInteractionRequest request) throws Exception {
            HttpRequest req = buildRequest(request, CreateInteractionRequest.class, new TypeReference<CreateInteractionRequest>() {});
            return sdkConfiguration.hooks().beforeRequest(createBeforeRequestContext(), req);
        }

        private HttpResponse<InputStream> onError(HttpResponse<InputStream> response, Exception error) throws Exception {
            return sdkConfiguration.hooks().afterError(
                    createAfterErrorContext(),
                    Optional.ofNullable(response),
                    Optional.ofNullable(error));
        }

        private HttpResponse<InputStream> onSuccess(HttpResponse<InputStream> response) throws Exception {
            return sdkConfiguration.hooks().afterSuccess(createAfterSuccessContext(), response);
        }

        @Override
        public HttpResponse<InputStream> doRequest(CreateInteractionRequest request) {
            Retries retries = Retries.builder()
                    .action((attempt) -> {
                        HttpRequest r;
                        try {
                            r = onBuildRequest(request);
                        } catch (Exception e) {
                            throw new NonRetryableException(e);
                        }
                        try {
                            HttpResponse<InputStream> httpRes = client.send(r);
                            if (Utils.statusCodeMatches(httpRes.statusCode(), "4XX", "5XX")) {
                                return onError(httpRes, null);
                            }
                            return httpRes;
                        } catch (Exception e) {
                            return onError(null, e);
                        }
                    })
                    .retryConfig(retryConfig)
                    .statusCodes(retryStatusCodes)
                    .build();
            return unchecked(() -> onSuccess(retries.run())).get();
        }


        @Override
        public CreateInteractionResponse handleResponse(HttpResponse<InputStream> response) {
            String contentType = response
                    .contentType()
                    .orElse("application/octet-stream");
            CreateInteractionResponse.Builder resBuilder =
                    CreateInteractionResponse
                            .builder()
                            .contentType(contentType)
                            .statusCode(response.statusCode())
                            .rawResponse(response);

            CreateInteractionResponse res = resBuilder.build();
            
            if (Utils.statusCodeMatches(response.statusCode(), "200")) {
                if (Utils.contentTypeMatches(contentType, "application/json")) {
                    return res.withInteraction(Utils.unmarshal(response, new TypeReference<Interaction>() {}));
                }
            if (Utils.contentTypeMatches(contentType, "text/event-stream")) {
                    Utils.setSseSentinel(res, "[DONE]");
                    return res;
                } else {
                    throw GaosApiException.from("Unexpected content-type received: " + contentType, response);
                }
            }
            if (Utils.statusCodeMatches(response.statusCode(), "4XX")) {
                if (Utils.contentTypeMatches(contentType, "application/json")) {
                    throw CreateInteractionClientError.from(response);
                } else {
                    throw GaosApiException.from("Unexpected content-type received: " + contentType, response);
                }
            }
            if (Utils.statusCodeMatches(response.statusCode(), "5XX")) {
                if (Utils.contentTypeMatches(contentType, "application/json")) {
                    throw CreateInteractionServerError.from(response);
                } else {
                    throw GaosApiException.from("Unexpected content-type received: " + contentType, response);
                }
            }
            throw GaosApiException.from("Unexpected status code received: " + response.statusCode(), response);
        }
    }
    public static class Async extends Base
            implements AsyncRequestOperation<CreateInteractionRequest, com.google.genai.gaos.models.operations.async.CreateInteractionResponse> {
        private final ScheduledExecutorService retryScheduler;

        public Async(
                @Nonnull SDKConfiguration sdkConfiguration, @Nullable Options options,
                @Nullable ScheduledExecutorService retryScheduler, Headers _headers) {
            super(
                  sdkConfiguration, options,
                  _headers);
            this.retryScheduler = retryScheduler;
        }

        private final Operations.CancellationRelay cancellationRelay = new Operations.CancellationRelay();

        @Override
        public Operations.CancellationRelay cancellationRelay() {
            return cancellationRelay;
        }

        private CompletableFuture<HttpRequest> onBuildRequest(CreateInteractionRequest request) throws Exception {
            HttpRequest req = buildRequest(request, CreateInteractionRequest.class, new TypeReference<CreateInteractionRequest>() {});
            return this.sdkConfiguration.asyncHooks().beforeRequest(createBeforeRequestContext(), req);
        }

        private CompletableFuture<HttpResponse<InputStream>> onError(HttpResponse<InputStream> response, Throwable error) {
            return this.sdkConfiguration.asyncHooks().afterError(createAfterErrorContext(), response, error);
        }

        private CompletableFuture<HttpResponse<InputStream>> onSuccess(HttpResponse<InputStream> response) {
            return this.sdkConfiguration.asyncHooks().afterSuccess(createAfterSuccessContext(), response);
        }

        @Override
        public CompletableFuture<HttpResponse<InputStream>> doRequest(CreateInteractionRequest request) {
            AsyncRetries retries = AsyncRetries.builder()
                    .retryConfig(retryConfig)
                    .statusCodes(retryStatusCodes)
                    .scheduler(retryScheduler)
                    .build();
            return retries.retry((attempt) -> unchecked(() -> onBuildRequest(request)).get()
                            .thenCompose(req -> cancellationRelay.track(client.sendAsync(req)))
                            .handle((resp, err) -> {
                                if (err != null) {
                                    return onError(null, err);
                                }
                                if (Utils.statusCodeMatches(resp.statusCode(), "4XX", "5XX")) {
                                    return onError(resp, null);
                                }
                                return CompletableFuture.completedFuture(resp);
                            })
                            .thenCompose(Function.identity()))
                    .thenCompose(this::onSuccess);
        }

        @Override
        public com.google.genai.gaos.models.operations.async.CreateInteractionResponse handleResponse(HttpResponse<InputStream> response) {
            String contentType = response
                    .contentType()
                    .orElse("application/octet-stream");
            com.google.genai.gaos.models.operations.async.CreateInteractionResponse.Builder resBuilder =
                    com.google.genai.gaos.models.operations.async.CreateInteractionResponse
                            .builder()
                            .contentType(contentType)
                            .statusCode(response.statusCode())
                            .rawResponse(response);

            com.google.genai.gaos.models.operations.async.CreateInteractionResponse res = resBuilder.build();
            
            if (Utils.statusCodeMatches(response.statusCode(), "200")) {
                if (Utils.contentTypeMatches(contentType, "application/json")) {
                    return res.withInteraction(Utils.unmarshal(response, new TypeReference<Interaction>() {}));
                }
            if (Utils.contentTypeMatches(contentType, "text/event-stream")) {
                    Utils.setSseSentinel(res, "[DONE]");
                    return res;
                } else {
                    throw GaosApiException.from("Unexpected content-type received: " + contentType, response);
                }
            }
            if (Utils.statusCodeMatches(response.statusCode(), "4XX")) {
                if (Utils.contentTypeMatches(contentType, "application/json")) {
                    throw CreateInteractionClientError.from(response);
                } else {
                    throw GaosApiException.from("Unexpected content-type received: " + contentType, response);
                }
            }
            if (Utils.statusCodeMatches(response.statusCode(), "5XX")) {
                if (Utils.contentTypeMatches(contentType, "application/json")) {
                    throw CreateInteractionServerError.from(response);
                } else {
                    throw GaosApiException.from("Unexpected content-type received: " + contentType, response);
                }
            }
            throw GaosApiException.from("Unexpected status code received: " + response.statusCode(), response);
        }
    }
}
