/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.errors;

import java.io.InputStream;
import com.google.genai.gaos.utils.transport.HttpResponse;
import java.util.Optional;

/**
 * An exception associated with Authentication or Authorization.
 */
@SuppressWarnings("serial")
public class AuthException extends GaosClientException {

    public AuthException(String message, int code, byte[] body, HttpResponse<InputStream> rawResponse) {
       super(message, code, body, rawResponse, null);
    }

    /**
     * Returns the HTTP status code of the response.
     *
     * @deprecated Use {@link #code()} instead.
     */
    @Deprecated
    public Optional<Integer> statusCode() {
        return Optional.of(super.code());
    }
    
    @SuppressWarnings("unchecked")
    @Override
    public HttpResponse<InputStream> rawResponse() {
        return (HttpResponse<InputStream>) super.rawResponse();
    }
}
