/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.errors;

import com.google.genai.gaos.utils.Utils;
import com.google.genai.gaos.utils.Headers;

import jakarta.annotation.Nullable;

import com.google.genai.gaos.utils.transport.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.Optional;

@SuppressWarnings("serial")
public abstract class GaosBaseException extends com.google.genai.errors.ApiException {

    private int code;
    private byte[] body;
    private HttpResponse<?> rawResponse;

    public GaosBaseException(String message, int code, @Nullable byte[] body, HttpResponse<?> rawResponse, @Nullable Throwable cause) {
        super(code, "", message, cause);
        Utils.checkNotNull(message, "message");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.body = body;
        this.code = code;
        this.rawResponse = rawResponse;
    }
    
    public Optional<byte[]> body() {
        return Optional.ofNullable(body);
    }
    
    public Optional<String> bodyAsString() {
        return body().map(x -> new String(x, StandardCharsets.UTF_8));
    }
    
    public int code() {
        return code;
    }
    
    /**
     * Returns the raw HTTP response associated with this exception. The response body stream
     * may not be available (but the body can be accessed via the {@code body()} method).
     * 
     * @return the raw HTTP response
     */
    public HttpResponse<?> rawResponse() {
        return rawResponse;
    }
    
    /**
     * Returns the headers from the raw HTTP response as a map.
     * 
     * @return response headers
     */
    public Headers headers() {
        return new Headers(rawResponse.headers().map());
    }
    
    // present for backwards compatibility
    public String message() {
        return getMessage();
    }
    
    public GaosBaseException withCode(int code) {
        this.code = code;
        return this;
    }
    
    public GaosBaseException withBody(@Nullable byte[] body) {
        Utils.checkNotNull(body, "body");
        this.body = body;
        return this;
    }
    
    public GaosBaseException withRawResponse(HttpResponse<?> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public String toString() {
        return Utils.toString(this.getClass(),
                "requestMethod", rawResponse.request().method(),
                "requestUri", rawResponse.request().uri(),
                "code", code,
                "responseHeaders", rawResponse.headers().map(), 
                "message", getMessage(),
                "body", bodyAsString().orElse("null"));
    }
}

