/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.errors;

import jakarta.annotation.Nullable;
import com.google.genai.gaos.utils.Utils;

import java.io.IOException;
import java.io.InputStream;
import com.google.genai.gaos.utils.transport.HttpResponse;

/**
 * Thrown by a service call when an error response occurs. Contains details about the response.
 */
@SuppressWarnings("serial")
public class GaosApiException extends GaosBaseException {

    public GaosApiException(
            String message,
            int code,
            @Nullable byte[] body,
            HttpResponse<InputStream> rawResponse,
            @Nullable Throwable cause) {
        super(message, code, body, rawResponse, cause);
    }

    public static GaosApiException from(String message, HttpResponse<InputStream> rawResponse) {
        return from(message, rawResponse, null);
    }

    public static GaosApiException from(String message, HttpResponse<InputStream> rawResponse, @Nullable Throwable cause) {
        try {
            return new GaosApiException(
                    message, rawResponse.statusCode(), Utils.extractByteArrayFromBody(rawResponse), rawResponse, cause);
        } catch (IOException e) {
            // Gracefully handle IOExceptions that occur while reading the body
            // by returning an error without a body.
            return new GaosApiException(
                    message, rawResponse.statusCode(), null, rawResponse, cause);
        }
    }
    
    @SuppressWarnings("unchecked")
    @Override
    public HttpResponse<InputStream> rawResponse() {
        return (HttpResponse<InputStream>) super.rawResponse();
    }
}
