/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.models.interactions.Error;
import com.google.genai.gaos.utils.Utils;
import com.google.genai.gaos.utils.transport.HttpResponse;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Deprecated;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.lang.Throwable;
import java.util.Optional;

@SuppressWarnings("serial")
public class GetInteractionByIdServerError extends GaosServerException {

    @Nullable
    private final Data data;

    @Nullable
    private final Throwable deserializationException;

    public GetInteractionByIdServerError(
                int code,
                byte[] body,
                HttpResponse<?> rawResponse,
                @Nullable Data data,
                @Nullable Throwable deserializationException) {
        super("API error occurred", code, body, rawResponse, null);
        this.data = data;
        this.deserializationException = deserializationException;
    }

    /**
    * Parse a response into an instance of GetInteractionByIdServerError. If deserialization of the response body fails,
    * the resulting GetInteractionByIdServerError instance will have a null data() value and a non-null deserializationException().
    */
    public static GetInteractionByIdServerError from(HttpResponse<InputStream> response) {
        try {
            byte[] bytes = Utils.extractByteArrayFromBody(response);
            Data data = Utils.mapper().readValue(bytes, Data.class);
            return new GetInteractionByIdServerError(response.statusCode(), bytes, response, data, null);
        } catch (Exception e) {
            return new GetInteractionByIdServerError(response.statusCode(), null, response, null, e);
        }
    }

    /**
     * Error message from an interaction.
     */
    @Deprecated
    public Optional<Error> error() {
        return data().flatMap(Data::error);
    }

    public Optional<Data> data() {
        return Optional.ofNullable(data);
    }

    /**
     * Returns the exception if an error occurs while deserializing the response body.
     */
    public Optional<Throwable> deserializationException() {
        return Optional.ofNullable(deserializationException);
    }
    /**
     * Data
     * 
     * <p>Error getting interaction
     */
    public static class Data {
        /**
         * Error message from an interaction.
         */
        @JsonProperty("error")
        private Error error;

        @JsonCreator
        public Data(
                @JsonProperty("error") @Nonnull Error error) {
            this.error = Optional.ofNullable(error)
                .orElseThrow(() -> new IllegalArgumentException("error cannot be null"));
        }

        /**
         * Error message from an interaction.
         */
        public Optional<Error> error() {
            return Optional.ofNullable(this.error);
        }

        public static Builder builder() {
            return new Builder();
        }


        /**
         * Error message from an interaction.
         */
        public Data withError(@Nonnull Error error) {
            this.error = Utils.checkNotNull(error, "error");
            return this;
        }


        @Override
        public boolean equals(java.lang.Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Data other = (Data) o;
            return 
                Utils.enhancedDeepEquals(this.error, other.error);
        }
        
        @Override
        public int hashCode() {
            return Utils.enhancedHash(
                error);
        }
        
        @Override
        public String toString() {
            return Utils.toString(Data.class,
                    "error", error);
        }

        @SuppressWarnings("UnusedReturnValue")
        public final static class Builder {

            private Error error;

            private Builder() {
              // force use of static builder() method
            }

            /**
             * Error message from an interaction.
             */
            public Builder error(@Nonnull Error error) {
                this.error = Utils.checkNotNull(error, "error");
                return this;
            }

            public Data build() {
                return new Data(
                    error);
            }

        }
    }

}

